import sys
import warnings
from pyspark.context import SparkContext
from pyspark.sql import SparkSession, DataFrame, Window
import pyspark.sql.types as T 
import pyspark.sql.functions as F 
from pyspark.sql.functions import col
from awsglue.context import GlueContext
from awsglue.job import Job
import awsglue.transforms as GT
from awsglue.utils import getResolvedOptions
from awsglue.dynamicframe import DynamicFrame, DynamicFrameCollection


# turn off warning msgs
warnings.filterwarnings('ignore')


sc: SparkContext = SparkContext.getOrCreate()
sc.setLogLevel('ERROR')


spark: SparkSession = (
     SparkSession
     .builder
     .getOrCreate() # pyright:ignore
)

spark.version


glue: GlueContext = GlueContext(sc)
job: Job = Job(glue)


params: list[str] = []
if '--JOB_NAME' in sys.argv:
    params += ['JOB_NAME']
args = getResolvedOptions(sys.argv, params)
jobname: str = args.get('JOB_NAME', 'test')
job.init(jobname, args)


# tx ======
df_tx: DataFrame = (
    spark 
    .read 
    .options(header='true', inferSchema='true')
    .csv('file:///home/hadoop/workspace/data/transactions_data.csv')
)


# show sample of data
df_tx.limit(5).show()

# schema
df_tx.printSchema()

# total row count 
df_tx.count()

# show N/A values 
(
    df_tx
    .select(
        [ F.count(F.when(F.col(c).isNull() | (F.col(c) == ""), 1)).alias(c) 
          for c in df_tx.columns ]
    )
    .show()
)

# replace $ in the amount value
df_tx = ( 
    df_tx
    .withColumn(
        'amount', 
        F.regexp_replace('amount', r'\$', '').cast(T.FloatType() )
    )
)


# check merchant_state
df_tx_empty_state = df_tx.where(F.col('merchant_state').isNull())
df_tx_empty_state.select('merchant_city').distinct().show()
# fix
df_tx = (
    df_tx
    .withColumn(
        'merchant_state', 
        F.when(col('merchant_city') == 'ONLINE', 'ONLINE')
            .otherwise(col('merchant_state') ) 
    )
)

# check errors
df_tx.select(F.explode(F.split('errors', ','))).distinct().show()
# fix
df_tx = df_tx.fillna('NO ERROR', subset=['errors'])


# fix zip 
df_tx: DataFrame = df_tx.withColumn('zip', F.col('zip').cast(T.StringType()))
# step 1
df_tx = (
    df_tx
    .withColumn(
        'zip', 
        F.when(col('merchant_city') == 'ONLINE', 'N/A')
        .otherwise(col('zip'))
    )
)

# update N/A 
# step 2. from equivalent city/state
win = Window.partitionBy('merchant_city','merchant_state')
df_tx = df_tx.withColumn('zip', F.first_value('zip', ignoreNulls=True).over(win))
# df_tx.where(F.col('zip').isNull()).count()

# step 3.
# find all tx where zip is null
df_tx_empty_zip = df_tx.where(F.col('zip').isNull())
# save city,state w/ nullable zip 
df_tx_empty_zip_merch = (
    df_tx_empty_zip
    .where(col('merchant_city') != 'ONLINE')
    .select('merchant_city', 'merchant_state')
    .distinct()
)
df_tx_empty_zip_merch.coalesce(1).write.csv('file:///home/hadoop/workspace/output/empty_zip.csv')


# zip codes for the merchant locations with no zip codes generated by LLM
df_missing_zip = (
    spark
    .read
    .option('header', 'true')
    .option('inferSchema', 'true')
    .csv('file:///home/hadoop/workspace/data/postal_codes.csv')
)
# explor missing zip
df_missing_zip.printSchema()
df_missing_zip.show()


df_tx = df_tx.alias('tx')
df_missing_zip = df_missing_zip.alias('mis')

df_tx = ( 
    df_tx
    .join(
        df_missing_zip,
        (col('tx.merchant_city') == col('mis.city')) & (col('tx.merchant_state') == col('mis.country')),
        how='left'
    )
    .withColumn('newzip', F.coalesce('tx.zip', 'mis.zip'))
    .drop('zip')
    .select('tx.*', col('newzip').alias('zip'))
)

# check null zip count
df_tx.where(col('zip').isNull()).count()

# WRITE: tx
# df_tx.write.parquet('file:///home/hadoop/workspace/output/transactions.parquet')


# EXPLOR: users ======
df_users = spark.read.option('header', 'true').option('inferSchema', 'true').csv('file:///home/hadoop/workspace/data/users_data.csv')


df_users.count()

df_users.limit(10).show()


df_users.printSchema()

# check for NA 
df_users.select([F.count(F.when(F.col(c).isNull() | (F.col(c) == ""), 1)).alias(c) for c in df_users.columns]).show()

# print summary 
df_users.summary().show()


# check gender 
df_users.select('gender').distinct().show()

# fix per_capita_income, yearly_income, total_debt
# remove $ prefix 
df_users = df_users.withColumns({
    c : F.regexp_replace(c, r'\$', '').cast(T.FloatType()) for c in ['per_capita_income','yearly_income','total_debt']
})

# recalculate current_age
df_users = df_users.withColumn('current_age', F.year(F.current_date()) - F.col('birth_year') - F.when(F.month(F.current_date()) - F.col('birth_month') >= 0, 0).otherwise(1) )

# time left until retirement 
df_users = df_users.withColumn('is_retired', F.col('current_age') >= F.col('retirement_age'))

df_users.where(F.col('is_retired') == True).limit(4).show()


# EXPLOR: cards ======
df_cards: DataFrame = (
    spark
    .read
    .options(header='true', inferSchema='true')
    .csv('file:///home/hadoop/workspace/data/cards_data.csv')
)

# check schema
df_cards.printSchema()

# rows count
df_cards.count()

# sample data
df_cards.limit(5).show()

# summary info
df_cards.summary().show()

# check for N/A 
(
    df_cards
    .select( 
        [ F.count( F.when(col(c).isNull() | (col(c) == ""), 1) ).alias(c) 
              for c in df_cards.columns ]
    )
    .show()
)

# FIXES

# card_brand 
df_cards.groupBy('card_brand').count().show()

# card_type 
df_cards.groupBy('card_type').count().show()

# has_chip 
df_cards.groupBy('has_chip').count().show()

# credit_limit
df_cards = df_cards.withColumn('credit_limit', F.regexp_replace(col('credit_limit'), r'\$', '').cast(T.FloatType()))
df_cards.limit(5).show()

# card_on_dark_web
df_cards.groupBy('card_on_dark_web').count().show()


# expires 
df_cards = (
    df_cards
    .withColumn('expire_year', F.split("expires", "/").getItem(1).cast(T.IntegerType()) )
    .withColumn('expire_month', F.split("expires", "/").getItem(0).cast(T.IntegerType()) )
    .drop('expires')
)


# acct_open_date
df_cards = (
    df_cards
    .withColumn('acct_open_year', F.split('acct_open_date', '/').getItem(1).cast(T.IntegerType()) )
    .withColumn('acct_open_month', F.split('acct_open_date', '/').getItem(0).cast(T.IntegerType()) )
    .drop('acct_open_date')
)


# EXPLOR: mcc_codes ======

import json 
with open('/home/hadoop/workspace/data/mcc_codes.json', 'r') as fp:
    data: dict[str, str] = json.load(fp)
src = []
for k,v in data.items():
    src.append((k,v))


df_mcc_codes = (
    spark 
    .createDataFrame(src, ['mcc', 'desc'])
)

# show schema
df_mcc_codes.printSchema()

# show sample data
df_mcc_codes.limit(5).show()

# row counts
df_mcc_codes.count()

# null values
(
    df_mcc_codes
    .select(
        [ F.count( F.when(col(c).isNull() | (col(c) == ''), 1) ).alias(c) 
         for c in df_mcc_codes.columns ]
    )
    .show()
)

# duplicates 
df_mcc_codes = df_mcc_codes.drop_duplicates(['mcc'])

