finanalytics:
  outputs:
    dev:
      dbname: dev
      host: "{{ env_var('DBT_HOST') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5439
      schema: dwh
      threads: 1
      type: redshift
      user: "{{ env_var('DBT_USER') }}"
  target: dev
